Algoritmo "Desconto ao preço"
//Gere um pseudocódigo que aplique um desconto
//de 30% sobre o valor de um produto, recebido
//como entrada, e retorne o resultado da
//manipulação na saída padrão.
Var
produto , desconto: real


Inicio
Escreva("Qual o valor do produto? ")
leia(produto)
desconto <- 70/100 * produto
escreva("Bem o valor de seu produto é, ",produto," mas com o desconto fica " ,desconto)
Fimalgoritmo